services:

  remote-desktop:
    image: donowak/remote-desktop:lan
    container_name: vnc-remote-desktop
    restart: on-failure
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ipc: host
    ports:
      - 8080:8080
    environment:
      - VNC_PASSWORD=husarion
      - DISPLAY