# xhost +local:docker

x-net-config:
  &net-config
  network_mode: host
  ipc: host
  env_file: net.env

x-cpu-config:
  &cpu-config
  environment:
    - DISPLAY=${DISPLAY:?err}
    - LIBGL_ALWAYS_SOFTWARE=1

services:
  rviz:
    image: husarion/rviz2:humble-11.2.6-20230809
    <<: [ *net-config, *cpu-config ]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/default.rviz:/root/.rviz2/default.rviz