x-net-config:
  &net-config
  network_mode: host
  ipc: host
  env_file: net.env

services:
  ouster-lidar:
    image: husarion/ouster:humble
    container_name: ouster-ros
    <<: *net-config
    command: >
      ros2 launch ouster_ros sensor.composite.launch.xml
        timestamp_mode:=TIME_FROM_ROS_TIME
        metadata:=/ouster_metadata.json
        viz:=false
        sensor_hostname:=10.15.20.5
        lidar_mode:=1024x20