services:

  ouster-lidar:
    image: husarion/ouster:melodic
    container_name: ouster-ros
    restart: unless-stopped
    network_mode: host
    environment:
      - ROS_IP=10.15.20.3
      - ROS_MASTER_URI=http://10.15.20.2:11311
    command: >
      roslaunch ouster_ros sensor.launch
        timestamp_mode:=TIME_FROM_PTP_1588
        metadata:=/ouster_metadata.json
        viz:=false
        sensor_hostname:=10.15.20.5
        lidar_mode:=1024x20