ARG ROS_DISTRO=jazzy

FROM ros:${ROS_DISTRO}-ros-core

RUN apt update && apt install -y \
        ros-${ROS_DISTRO}-rviz2 \
        ros-${ROS_DISTRO}-rmw-cyclonedds-cpp && \
    rm -rf /var/lib/apt/lists/*