name: Build/Publish Docker Image

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      tag:
        description: "A tag that the image will be built with"
        required: true
        default: "melodic"
      branch:
        description: "A branch that will be used to build the image"
        required: true
        default: "main"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push base tag
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64, linux/amd64
          push: true
          tags: husarion/ouster:${{ github.event.inputs.tag }}
          cache-from: type=registry,ref=husarion/ouster:melodic
          cache-to: type=inline
